import { Product, Coupon, CustomerReview } from '../types';
import { inferCategoryHierarchy } from '../utils/clothingSizes';

const rawInitialProducts: Product[] = [
  // ==========================================
  // 1. VINAYAK COLLECTION (Fashion & Clothing)
  // ==========================================
  {
    id: 'vc-shirt-01',
    sku: 'VC-MSH-001',
    name: "Men's Premium Linen Cotton Casual Shirt",
    shopId: 'vinayak-collection',
    categoryId: 'shirts',
    categoryName: 'Shirts',
    subcategoryId: 'mens-shirts',
    subcategoryName: "Men's Casual Shirts",
    brand: 'Vinayak Originals',
    description: 'Elevate your everyday wardrobe with our bespoke handcrafted breathable linen cotton shirt. Tailored with a smart mandarin collar, curved hem, and mother-of-pearl buttons. Ideal for Indian summers, festive gatherings, and office casual wear.',
    shortDescription: '100% Breathable pure cotton linen blend casual shirt.',
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1603252109303-2751441dd157?q=80&w=800&auto=format&fit=crop',
    ],
    price: 799,
    salePrice: 399,
    discount: 50,
    stock: 45,
    rating: 4.8,
    reviewsCount: 128,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    status: 'active',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-15T12:00:00Z',
    variants: [
      { type: 'size', name: 'Size', values: ['S', 'M', 'L', 'XL', 'XXL'] },
      { type: 'color', name: 'Color', values: ['Ivory White', 'Beige', 'Sky Blue', 'Olive Green'] },
    ],
    specifications: [
      { label: 'Fabric', value: '100% Cotton Linen Blend' },
      { label: 'Fit', value: 'Regular Comfort Fit' },
      { label: 'Sleeve', value: 'Full Sleeve with Roll-up Tab' },
      { label: 'Collar', value: 'Mandarin / Band Collar' },
      { label: 'Care Instructions', value: 'Machine wash warm, iron while damp' },
    ],
    clothingDetails: {
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Ivory White', 'Beige', 'Sky Blue', 'Olive Green'],
      fabric: '100% Cotton Linen',
    },
  },
  {
    id: 'vc-kurti-02',
    sku: 'VC-KUR-002',
    name: 'Pure Chanderi Silk Embroidered Kurti with Pant & Dupatta Set',
    shopId: 'vinayak-collection',
    categoryId: 'kurtis',
    categoryName: 'Kurtis & Sets',
    subcategoryId: 'kurta-sets',
    subcategoryName: 'Kurta Sets',
    brand: 'Vinayak Ethnic',
    description: 'Exquisite festive 3-piece designer ethnic ensemble crafted in luminous Chanderi silk. Adorned with delicate Zari and Gota Patti embroidery on the neckline, paired with tailored straight-cut pants and an organza floral printed dupatta.',
    shortDescription: '3-Piece festive handcrafted Chanderi suit with organza dupatta.',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop',
    ],
    price: 2599,
    salePrice: 1299,
    discount: 50,
    stock: 28,
    rating: 4.9,
    reviewsCount: 84,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    status: 'active',
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-03-16T12:00:00Z',
    variants: [
      { type: 'size', name: 'Size', values: ['M (38)', 'L (40)', 'XL (42)', 'XXL (44)'] },
      { type: 'color', name: 'Color', values: ['Royal Mustard Yellow', 'Emerald Green', 'Rani Pink'] },
    ],
    specifications: [
      { label: 'Kurta Fabric', value: 'Chanderi Silk with Cotton Lining' },
      { label: 'Bottom Fabric', value: 'Pure Cotton Silk Pant' },
      { label: 'Dupatta', value: 'Pure Organza with Golden Border' },
      { label: 'Length', value: 'Calf Length (46 inches)' },
      { label: 'Work', value: 'Handcrafted Zari & Sequins' },
    ],
    clothingDetails: {
      sizes: ['M (38)', 'L (40)', 'XL (42)', 'XXL (44)'],
      colors: ['Royal Mustard Yellow', 'Emerald Green', 'Rani Pink'],
      fabric: 'Chanderi Silk',
    },
  },
  {
    id: 'vc-tee-03',
    sku: 'VC-TEE-003',
    name: "Men's Heavyweight Oversized Graphic Streetwear T-Shirt",
    shopId: 'vinayak-collection',
    categoryId: 't-shirts',
    categoryName: 'T-Shirts',
    subcategoryId: 'oversize-tshirts',
    subcategoryName: 'Oversize T-Shirts',
    brand: 'Vinayak Raw',
    description: 'Premium 240 GSM combed ring-spun cotton oversized t-shirt designed for contemporary street culture. Features dropped shoulders, high rib neckband, and long-lasting high-density screen print.',
    shortDescription: '240 GSM drop-shoulder heavyweight streetwear t-shirt.',
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1581655353564-df123a1eb820?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=800&auto=format&fit=crop',
    ],
    price: 899,
    salePrice: 449,
    discount: 50,
    stock: 50,
    rating: 4.7,
    reviewsCount: 96,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    status: 'active',
    createdAt: '2026-03-12T08:00:00Z',
    updatedAt: '2026-03-12T08:00:00Z',
    variants: [
      { type: 'size', name: 'Size', values: ['M', 'L', 'XL', 'XXL'] },
      { type: 'color', name: 'Color', values: ['Black', 'White', 'Blue', 'Red', 'Green', 'Maroon'] },
    ],
    clothingDetails: {
      sizes: ['M', 'L', 'XL', 'XXL'],
      colors: ['Black', 'White', 'Blue', 'Red', 'Green', 'Maroon'],
      fabric: '240 GSM Pure Combed Cotton',
    },
    color_variants: [
      { name: 'Black', hex: '#171717', imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop' },
      { name: 'White', hex: '#FFFFFF', imageUrl: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?q=80&w=800&auto=format&fit=crop' },
      { name: 'Blue', hex: '#2563EB', imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=800&auto=format&fit=crop' },
      { name: 'Red', hex: '#DC2626', imageUrl: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=800&auto=format&fit=crop' },
      { name: 'Green', hex: '#16A34A', imageUrl: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?q=80&w=800&auto=format&fit=crop' },
      { name: 'Maroon', hex: '#800000', imageUrl: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=800&auto=format&fit=crop' },
    ],
    wholesale_mix_colors: ['Black', 'White', 'Blue', 'Red', 'Green', 'Maroon'],
    wholesale_set_type: 'MIX COLOR SET',
    wholesale_available_sizes: ['M', 'L', 'XL', 'XXL'],
    specifications: [
      { label: 'Weight', value: '240 GSM Heavy Cotton' },
      { label: 'Fit', value: 'Boxy Oversized Fit' },
      { label: 'Neck', value: 'Durable Ribbed Crew Neck' },
      { label: 'Wash Care', value: 'Cold machine wash inside out' },
    ],
  },
  {
    id: 'vc-cordset-04',
    sku: 'VC-CRD-004',
    name: "Women's Printed Cotton Co-Ord Set (Top & Trousers)",
    shopId: 'vinayak-collection',
    categoryId: 'cordsets',
    categoryName: 'Cordsets & Western',
    subcategoryId: 'cordsets',
    subcategoryName: 'Cordsets',
    brand: 'Vinayak Western',
    description: 'Chic matching co-ord set featuring a relaxed button-down tunic top with belt detailing and tapered ankle-length trousers with elasticated waistband. Breathable 100% Jaipur block printed cotton.',
    shortDescription: 'Trendy 2-piece cotton co-ord set for daily styling and travel.',
    images: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=800&auto=format&fit=crop',
    ],
    price: 1799,
    salePrice: 899,
    discount: 50,
    stock: 22,
    rating: 4.8,
    reviewsCount: 42,
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
    status: 'active',
    createdAt: '2026-03-14T09:00:00Z',
    updatedAt: '2026-03-14T09:00:00Z',
    variants: [
      { type: 'size', name: 'Size', values: ['S (36)', 'M (38)', 'L (40)', 'XL (42)'] },
      { type: 'color', name: 'Color', values: ['Indigo Boho Print', 'Terracotta Floral', 'Olive Geometry'] },
    ],
    specifications: [
      { label: 'Material', value: '100% Pure Cotton' },
      { label: 'Includes', value: '1 Button Tunic Top + 1 Trousers' },
      { label: 'Waistband', value: 'Elasticated with Drawstring' },
    ],
  },
  {
    id: 'vc-jeans-05',
    sku: 'VC-JNS-005',
    name: 'Premium Slim Fit Stretchable Denim Jeans',
    shopId: 'vinayak-collection',
    categoryId: 'jeans',
    categoryName: 'Jeans & Denim',
    subcategoryId: 'mens-jeans',
    subcategoryName: "Men's Jeans",
    brand: 'Vinayak Denim Co.',
    description: 'Crafted with premium Turkish weave ring-spun cotton infused with 2% elastane for unrestricted all-day flex. Hand-whiskered vintage fade wash with reinforced double stitch construction.',
    shortDescription: 'Super-comfortable stretch denim with durable stitch finish.',
    images: [
      'https://images.unsplash.com/photo-1542272604-780c96856592?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop',
    ],
    price: 1599,
    salePrice: 799,
    discount: 50,
    stock: 35,
    rating: 4.6,
    reviewsCount: 110,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    status: 'active',
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
    variants: [
      { type: 'size', name: 'Waist Size', values: ['28', '30', '32', '34', '36', '38'] },
      { type: 'color', name: 'Shade', values: ['Dark Indigo', 'Mid Blue Vintage', 'Charcoal Black'] },
    ],
    specifications: [
      { label: 'Fabric Composition', value: '98% Cotton, 2% Elastane' },
      { label: 'Fit Type', value: 'Slim Fit' },
      { label: 'Rise', value: 'Mid Rise' },
      { label: 'Closure', value: 'Heavy Duty Metal Zipper Fly' },
    ],
  },
  {
    id: 'vc-lower-06',
    sku: 'VC-LWR-006',
    name: "Men's Breathable Gym Track Lower / Joggers",
    shopId: 'vinayak-collection',
    categoryId: 'lowers',
    categoryName: 'Lowers & Joggers',
    subcategoryId: 'track-pants',
    subcategoryName: 'Track Pants',
    brand: 'Vinayak Sports',
    description: 'Engineered 4-way stretch poly-spandex moisture wicking gym track pants. Designed with dual deep zipper pockets, an athletic ribbed cuff, and an adjustable interior drawstring.',
    shortDescription: '4-Way stretch activewear lower with dual zipper pockets.',
    images: [
      'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?q=80&w=800&auto=format&fit=crop',
    ],
    price: 799,
    salePrice: 399,
    discount: 50,
    stock: 60,
    rating: 4.7,
    reviewsCount: 75,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    status: 'active',
    createdAt: '2026-03-05T10:00:00Z',
    updatedAt: '2026-03-05T10:00:00Z',
    variants: [
      { type: 'size', name: 'Size', values: ['M (30-32)', 'L (32-34)', 'XL (34-36)', 'XXL (36-38)'] },
      { type: 'color', name: 'Color', values: ['Anthracite Grey', 'Navy Blue', 'Deep Black'] },
    ],
    specifications: [
      { label: 'Fabric', value: 'Dry-Fit Poly Spandex' },
      { label: 'Pockets', value: '2 Side Zipper Pockets + 1 Back Pocket' },
      { label: 'Ideal For', value: 'Gym, Running, Travel & Lounge' },
    ],
  },

  // ==========================================
  // 2. KINSHUK SPARE PARTS (Bike Spare Parts & Accessories)
  // ==========================================
  {
    id: 'ksp-holder-01',
    sku: 'KSP-HLD-001',
    name: 'Waterproof All-Metal Bike Mobile Holder with USB Fast Charger',
    shopId: 'kinshuk-spare-parts',
    categoryId: 'mobile-holders',
    categoryName: 'Mobile Holders',
    subcategoryId: 'bike-accessories',
    subcategoryName: 'Handlebar Mounts',
    brand: 'Kinshuk Pro Rider',
    description: 'Aerospace-grade CNC aluminium alloy motorcycle phone mount featuring an integrated 5V/2.5A USB quick-charger. Designed with 360-degree ball rotation and 4-jaw mechanical locking system to securely hold phones on rough highways and off-road tracks.',
    shortDescription: 'CNC Aluminium 360° bike mount with integrated USB quick charger.',
    images: [
      'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?q=80&w=800&auto=format&fit=crop',
    ],
    price: 999,
    salePrice: 499,
    discount: 50,
    stock: 55,
    rating: 4.9,
    reviewsCount: 164,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    status: 'active',
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-03-10T11:00:00Z',
    variants: [
      { type: 'bikeModel', name: 'Handlebar Clamp Size', values: ['Standard 22mm (7/8")', 'Fat Bar 28mm (1-1/8")', 'Mirror Mount Base'] },
      { type: 'color', name: 'Finish', values: ['Matte Black', 'Silver Metallic'] },
    ],
    specifications: [
      { label: 'Material', value: 'CNC Anodized Aluminium 6061' },
      { label: 'Charging Output', value: '5V / 2.4A Fast USB Port with Waterproof Cap' },
      { label: 'Supported Phone Size', value: '4.7 inches to 7.2 inches' },
      { label: 'Compatibility', value: 'Splendor, Pulsar, Apache, Royal Enfield, Duke, Activa, Jupiter' },
      { label: 'Warranty', value: '6 Months Replacement Warranty' },
    ],
    bikeDetails: {
      compatibleBrands: ['Hero', 'Bajaj', 'TVS', 'Honda', 'Royal Enfield', 'Yamaha', 'KTM'],
      compatibleModels: ['All Standard Motorcycles & Scooters'],
      material: 'Aircraft Grade Aluminium',
    },
  },
  {
    id: 'ksp-foglight-02',
    sku: 'KSP-LGT-002',
    name: 'Universal Dual Color LED Fog Light Projector with Flasher (Pair)',
    shopId: 'kinshuk-spare-parts',
    categoryId: 'lights',
    categoryName: 'Lights & Indicators',
    subcategoryId: 'fog-lights',
    subcategoryName: 'LED Fog Lights',
    brand: 'Kinshuk Pro Rider',
    description: 'High-intensity 60W bi-focal projector auxiliary lights. Emits crisp Amber Yellow for heavy rain/dense fog navigation and High Beam Pure White 6000K for dark highway illumination. IP68 certified waterproof casing with heat-sink cooling ribs.',
    shortDescription: '60W Dual Color (Amber/White) waterproof highway auxiliary fog lights.',
    images: [
      'https://images.unsplash.com/photo-1615172282427-9a57ef2d142e?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?q=80&w=800&auto=format&fit=crop',
    ],
    price: 1599,
    salePrice: 799,
    discount: 50,
    stock: 32,
    rating: 4.8,
    reviewsCount: 142,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    status: 'active',
    createdAt: '2026-03-08T10:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
    variants: [
      { type: 'bikeModel', name: 'Mounting Bracket Type', values: ['Universal Leg Guard Clamp', 'Handlebar Clamp'] },
    ],
    specifications: [
      { label: 'Power Output', value: '60 Watts Total (Pair)' },
      { label: 'Light Modes', value: 'White Beam, Yellow Fog Beam, Strobe/Flasher' },
      { label: 'Waterproof Rating', value: 'IP68 Submersible' },
      { label: 'Operating Voltage', value: '9V - 85V DC' },
      { label: 'Luminous Flux', value: '6000 Lumens' },
    ],
    bikeDetails: {
      compatibleBrands: ['Royal Enfield', 'Bajaj', 'TVS', 'Hero', 'Yamaha', 'KTM'],
      compatibleModels: ['Classic 350', 'Hunter 350', 'Pulsar NS200', 'Apache RTR', 'Himalayan'],
      material: 'Die-Cast Heavy Metal Housing',
    },
  },
  {
    id: 'ksp-mirrors-03',
    sku: 'KSP-MIR-003',
    name: 'Premium Aerodynamic Rear View Mirrors with Anti-Glare Blue Tint (Pair)',
    shopId: 'kinshuk-spare-parts',
    categoryId: 'mirrors',
    categoryName: 'Mirrors & Styling',
    subcategoryId: 'mirrors',
    subcategoryName: 'Rear View Mirrors',
    brand: 'Kinshuk Pro Rider',
    description: 'Sleek diamond-cut aerodynamic rearview mirrors equipped with anti-glare blue optical glass to deflect high-beam headlights from trailing vehicles. Solid metal stem prevents vibration distortion at high speeds.',
    shortDescription: 'Anti-glare blue tint convex mirrors with heavy vibration-free metal stems.',
    images: [
      'https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?q=80&w=800&auto=format&fit=crop',
    ],
    price: 899,
    salePrice: 449,
    discount: 50,
    stock: 40,
    rating: 4.7,
    reviewsCount: 78,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    status: 'active',
    createdAt: '2026-02-18T10:00:00Z',
    updatedAt: '2026-02-28T10:00:00Z',
    variants: [
      { type: 'bikeModel', name: 'Thread Size', values: ['Universal 10mm Clockwise', 'Universal 8mm (Scooters)', 'Yamaha Thread (Reverse Left)'] },
      { type: 'color', name: 'Color', values: ['Carbon Fiber Texture', 'Midnight Matte Black'] },
    ],
    specifications: [
      { label: 'Glass Type', value: 'Anti-Glare Blue Convex Optical Glass' },
      { label: 'Stem Material', value: 'Heavy Duty Cast Iron with Powder Coating' },
      { label: 'Adjustment', value: '360° Ball Joint Angle Articulation' },
    ],
  },
  {
    id: 'ksp-seat-04',
    sku: 'KSP-SCT-004',
    name: 'Heavy-Duty Diamond Stitched Anti-Slip Breathable Bike Seat Cover',
    shopId: 'kinshuk-spare-parts',
    categoryId: 'seat-covers',
    categoryName: 'Bike Styling & Safety',
    subcategoryId: 'seat-covers',
    subcategoryName: 'Seat Covers',
    brand: 'Kinshuk Comfort',
    description: 'Custom molded ergonomic bike seat cover featuring 8mm high-density memory foam padding with honeycomb airflow 3D mesh. Protects against scorching direct sun heat, rain seepage, and tailbone strain during long commutes.',
    shortDescription: 'Honeycomb cooling mesh seat cover with memory foam padding.',
    images: [
      'https://images.unsplash.com/photo-1558981806-ec527fa84c39?q=80&w=800&auto=format&fit=crop',
    ],
    price: 599,
    salePrice: 299,
    discount: 50,
    stock: 75,
    rating: 4.6,
    reviewsCount: 94,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    status: 'active',
    createdAt: '2026-03-02T10:00:00Z',
    updatedAt: '2026-03-12T10:00:00Z',
    variants: [
      { type: 'bikeModel', name: 'Bike Model Compatibility', values: ['Hero Splendor / HF Deluxe', 'Honda Activa 5G/6G/125', 'Bajaj Pulsar 125/150', 'Royal Enfield Classic 350', 'TVS Jupiter / Raider'] },
      { type: 'color', name: 'Stitching Color', values: ['Red Thread Contrast', 'Gold Thread Contrast', 'All Black Stealth'] },
    ],
    specifications: [
      { label: 'Material', value: 'High Grade Heavy Rexine + 3D Honeycomb Mesh' },
      { label: 'Padding', value: '8mm High Resilient Cushion Foam' },
      { label: 'Fastening', value: 'Heavy Elastic Hem + Under-Seat Velcro Straps' },
    ],
  },
  {
    id: 'ksp-horn-05',
    sku: 'KSP-HRN-005',
    name: 'Loud Twin Tone Waterproof Electric Snail Horn 12V 110dB (Pair)',
    shopId: 'kinshuk-spare-parts',
    categoryId: 'horns',
    categoryName: 'Horns & Safety',
    subcategoryId: 'horns',
    subcategoryName: 'Electric Horns',
    brand: 'Kinshuk Pro Rider',
    description: 'Twin snail power acoustic horns delivering authoritative European-style dual frequency tones (510Hz High + 410Hz Low) at 110dB. Penetrates noisy traffic with immediate safety alert response. Comes with copper wiring relay kit.',
    shortDescription: '110dB loud European dual tone 12V snail horns with relay.',
    images: [
      'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=800&auto=format&fit=crop',
    ],
    price: 799,
    salePrice: 399,
    discount: 50,
    stock: 38,
    rating: 4.8,
    reviewsCount: 88,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    status: 'active',
    createdAt: '2026-02-25T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
    variants: [
      { type: 'color', name: 'Horn Shell Color', values: ['Gloss Black', 'Sport Red Chrome', 'Electroplated Silver'] },
    ],
    specifications: [
      { label: 'Decibel Level', value: '110 - 118 dB' },
      { label: 'Frequency', value: 'Dual 510Hz (High) & 410Hz (Low)' },
      { label: 'Voltage', value: '12 Volts DC' },
      { label: 'Weather Protection', value: 'Waterproof Drainage Shield' },
    ],
  },
  {
    id: 'ksp-indicator-06',
    sku: 'KSP-IND-006',
    name: 'LED Flowing Sequential Turn Signal Indicators with DRL (Set of 4)',
    shopId: 'kinshuk-spare-parts',
    categoryId: 'indicators',
    categoryName: 'Lights & Indicators',
    subcategoryId: 'indicators',
    subcategoryName: 'Indicators',
    brand: 'Kinshuk Pro Rider',
    description: 'Dynamic flowing matrix amber turn indicator blinkers combined with daytime running white LED glow. Flexible rubber mounting stem absorbs accidental impacts and prevents breakages.',
    shortDescription: 'Set of 4 dynamic flowing amber blinkers with flexible stem.',
    images: [
      'https://images.unsplash.com/photo-1615172282427-9a57ef2d142e?q=80&w=800&auto=format&fit=crop',
    ],
    price: 699,
    salePrice: 349,
    discount: 50,
    stock: 45,
    rating: 4.7,
    reviewsCount: 62,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    status: 'active',
    createdAt: '2026-03-11T10:00:00Z',
    updatedAt: '2026-03-11T10:00:00Z',
    variants: [
      { type: 'color', name: 'DRL Running Light Color', values: ['Cool White DRL', 'Electric Blue DRL', 'Warm Amber DRL'] },
    ],
    specifications: [
      { label: 'Quantity', value: 'Full Set of 4 Pieces (Front & Rear)' },
      { label: 'Thread Size', value: 'Standard 10mm Bolt Mount' },
      { label: 'Material', value: 'High Flexibility Acrylic & Elastic Rubber' },
    ],
  },

  // ==========================================
  // 3. KHUSHI COMMUNICATION (Mobiles & Accessories)
  // ==========================================
  {
    id: 'kc-charger-01',
    sku: 'KC-CHG-001',
    name: '65W GaN Super Fast USB-C Dual Port Wall Charger',
    shopId: 'khushi-communication',
    categoryId: 'chargers',
    categoryName: 'Chargers & Adapters',
    subcategoryId: 'fast-chargers',
    subcategoryName: 'Fast Chargers',
    brand: 'Khushi UltraPower',
    description: 'Next-generation Gallium Nitride (GaN III) high-efficiency travel adapter capable of powering laptops, MacBooks, iPhones, Samsung smartphones, and OnePlus devices. Supports Power Delivery 3.0, PPS, and Quick Charge 4+ with dynamic intelligent thermal control.',
    shortDescription: '65W GaN Dual Port (USB-C + USB-A) universal super fast adapter.',
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1585338107529-13afc5f02586?q=80&w=800&auto=format&fit=crop',
    ],
    price: 1499,
    salePrice: 699,
    discount: 53,
    stock: 65,
    rating: 4.9,
    reviewsCount: 189,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    status: 'active',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
    variants: [
      { type: 'color', name: 'Color', values: ['Pure Matte White', 'Midnight Piano Black'] },
      { type: 'warranty', name: 'Warranty Package', values: ['1 Year Comprehensive Warranty', '2 Year Extended Care (+₹99)'] },
    ],
    specifications: [
      { label: 'Output Power', value: 'Max 65 Watts GaN III' },
      { label: 'Ports', value: '1x Type-C (65W Max) + 1x Type-A (22.5W QC 3.0)' },
      { label: 'Protocols Supported', value: 'PD 3.0, PPS, QC 4+, Dash, Warp, SuperVOOC compatible' },
      { label: 'Safety Protections', value: 'Over-voltage, Short-circuit, Thermal throttling protection' },
      { label: 'Certification', value: 'BIS Certified for Indian Standards' },
    ],
    mobileDetails: {
      compatibleBrands: ['Apple iPhone', 'Samsung', 'OnePlus', 'Xiaomi', 'Realme', 'Vivo', 'Oppo', 'Google Pixel'],
      warrantyMonths: 12,
      colors: ['Pure Matte White', 'Midnight Piano Black'],
    },
  },
  {
    id: 'kc-powerbank-02',
    sku: 'KC-PWR-002',
    name: '20000mAh Power Bank with 22.5W Two-Way Fast Charging & LED Display',
    shopId: 'khushi-communication',
    categoryId: 'power-banks',
    categoryName: 'Power Banks',
    subcategoryId: 'power-banks',
    subcategoryName: 'High Capacity Power Banks',
    brand: 'Khushi UltraPower',
    description: 'High-density Lithium-Polymer 20000mAh external battery pack with dual USB output and Type-C input/output. Features an accurate digital percentage LED display, flight-approved casing, and intelligent smart trickle charging mode for smartwatches and TWS buds.',
    shortDescription: '20000mAh 22.5W fast charge battery with real-time numeric battery display.',
    images: [
      'https://images.unsplash.com/photo-1609592426860-22c6e3b08e2f?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1609592426915-d41c49622d1a?q=80&w=800&auto=format&fit=crop',
    ],
    price: 2499,
    salePrice: 1299,
    discount: 48,
    stock: 42,
    rating: 4.8,
    reviewsCount: 135,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    status: 'active',
    createdAt: '2026-02-22T10:00:00Z',
    updatedAt: '2026-03-05T10:00:00Z',
    variants: [
      { type: 'color', name: 'Color', values: ['Titanium Grey', 'Forest Green', 'Stealth Black'] },
    ],
    specifications: [
      { label: 'Capacity', value: '20000 mAh (74 Wh)' },
      { label: 'Max Output', value: '22.5W Fast Charge' },
      { label: 'Output Ports', value: '2x USB-A (22.5W) + 1x Type-C (20W PD)' },
      { label: 'Input Ports', value: 'Type-C & Micro-USB 18W Fast Recharge' },
      { label: 'Display', value: 'Digital LED Percentage Indicator' },
    ],
    mobileDetails: {
      compatibleBrands: ['All Smartphones, Tablets, Smartwatches & Bluetooth Devices'],
      warrantyMonths: 12,
    },
  },
  {
    id: 'kc-earbuds-03',
    sku: 'KC-EAR-003',
    name: 'Active Noise Cancelling (ANC) Wireless Bluetooth Earbuds',
    shopId: 'khushi-communication',
    categoryId: 'earphones',
    categoryName: 'Earphones & Audio',
    subcategoryId: 'tws-earbuds',
    subcategoryName: 'TWS Earbuds',
    brand: 'Khushi SoundMax',
    description: 'Immerse in studio fidelity acoustics powered by 12mm titanium drivers and 32dB Active Noise Cancellation. Features Quad Environmental Noise Cancelling (ENC) microphones for crystal clear calling in crowded Indian markets and transit.',
    shortDescription: '32dB ANC Bluetooth 5.4 earbuds with 40 hours total playtime.',
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?q=80&w=800&auto=format&fit=crop',
    ],
    price: 2799,
    salePrice: 1199,
    discount: 57,
    stock: 48,
    rating: 4.8,
    reviewsCount: 156,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    status: 'active',
    createdAt: '2026-03-04T10:00:00Z',
    updatedAt: '2026-03-14T10:00:00Z',
    variants: [
      { type: 'color', name: 'Color', values: ['Pearl White with Rose Gold', 'Carbon Black', 'Deep Navy'] },
    ],
    specifications: [
      { label: 'Noise Cancellation', value: '32dB Active Hybrid Noise Cancellation (ANC)' },
      { label: 'Bluetooth Version', value: 'Bluetooth 5.4 with Low Latency Gaming Mode (45ms)' },
      { label: 'Battery Life', value: '8 Hours Earbuds + 32 Hours Charging Case' },
      { label: 'Water Resistance', value: 'IPX5 Sweat & Splash Proof' },
    ],
    mobileDetails: {
      compatibleBrands: ['iOS, Android, Windows, Mac laptops and tablets'],
      warrantyMonths: 12,
    },
  },
  {
    id: 'kc-cable-04',
    sku: 'KC-CBL-004',
    name: 'Braided Fast Charging 100W Type-C to Type-C Cable (1.5m)',
    shopId: 'khushi-communication',
    categoryId: 'cables',
    categoryName: 'Cables & Data',
    subcategoryId: 'cables',
    subcategoryName: 'Type-C Cables',
    brand: 'Khushi UltraPower',
    description: 'Armored with 20,000+ bend-tested military grade nylon braiding, zinc alloy connectors, and an embedded E-Marker chip for optimal 100W Power Delivery charging and 480Mbps ultra-fast data transfer.',
    shortDescription: '100W E-Marker fast charging cable with unbreakable nylon braid.',
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=800&auto=format&fit=crop',
    ],
    price: 499,
    salePrice: 199,
    discount: 60,
    stock: 90,
    rating: 4.7,
    reviewsCount: 172,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    status: 'active',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-02-15T10:00:00Z',
    variants: [
      { type: 'color', name: 'Length & Color', values: ['1.5 Meter - Space Grey', '1.5 Meter - Crimson Red', '2.0 Meter Long (+₹50)'] },
    ],
    specifications: [
      { label: 'Max Power', value: '100 Watts (20V/5A)' },
      { label: 'Chipset', value: 'Integrated Smart E-Marker IC' },
      { label: 'Data Speed', value: '480 Mbps' },
      { label: 'Bend Durability', value: '25,000+ Bends Tested' },
    ],
  },
  {
    id: 'kc-cover-05',
    sku: 'KC-CVR-005',
    name: 'Military Grade Shockproof Magnetic Mobile Cover with Kickstand',
    shopId: 'khushi-communication',
    categoryId: 'mobile-covers',
    categoryName: 'Mobile Covers & Protection',
    subcategoryId: 'mobile-covers',
    subcategoryName: 'Armor Cases',
    brand: 'Khushi Shield',
    description: 'Dual layer polycarbonate and TPU drop-tested phone case with 360-degree rotating metal ring kickstand compatible with magnetic car mounts. Raised 1.5mm lips protect camera lenses and front glass.',
    shortDescription: 'Dual-layer shockproof armor cover with magnetic metal kickstand.',
    images: [
      'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?q=80&w=800&auto=format&fit=crop',
    ],
    price: 699,
    salePrice: 299,
    discount: 57,
    stock: 80,
    rating: 4.6,
    reviewsCount: 114,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    status: 'active',
    createdAt: '2026-03-09T10:00:00Z',
    updatedAt: '2026-03-09T10:00:00Z',
    variants: [
      { type: 'bikeModel', name: 'Phone Model', values: ['iPhone 15 / 15 Pro', 'iPhone 14 / 13', 'Samsung Galaxy S23 / S24', 'Redmi Note 13 Pro', 'Realme 12 Pro', 'OnePlus 12 / 12R'] },
      { type: 'color', name: 'Color', values: ['Matte Black', 'Armored Navy Blue', 'Military Dark Olive'] },
    ],
    specifications: [
      { label: 'Drop Protection', value: '10 Ft Military Grade Drop Certified' },
      { label: 'Kickstand', value: 'Zinc Alloy Ring Kickstand with 360° Rotation' },
      { label: 'Magnetic Base', value: 'Compatible with Car Phone Mounts' },
    ],
  },
  {
    id: 'kc-tempered-06',
    sku: 'KC-TMP-006',
    name: '9H Edge-to-Edge HD Tempered Glass Screen Protector with Easy Applicator (Pack of 2)',
    shopId: 'khushi-communication',
    categoryId: 'screen-protectors',
    categoryName: 'Mobile Covers & Protection',
    subcategoryId: 'screen-protectors',
    subcategoryName: 'Tempered Glass',
    brand: 'Khushi Shield',
    description: 'Japanese Asahi 9H hardness tempered glass with plasma oleophobic anti-fingerprint coating and seamless 2.5D curved arc edge. Comes with zero-bubble precision installation alignment tray.',
    shortDescription: 'Pack of 2 ultra-clear 9H tempered glass with auto-alignment kit.',
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=800&auto=format&fit=crop',
    ],
    price: 499,
    salePrice: 199,
    discount: 60,
    stock: 120,
    rating: 4.8,
    reviewsCount: 92,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    status: 'active',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-28T10:00:00Z',
    variants: [
      { type: 'bikeModel', name: 'Phone Screen Size / Model', values: ['iPhone 15 / 15 Pro', 'iPhone 14 / 13', 'Samsung A Series / S Series', 'OnePlus Nord / Flagship', 'Redmi / Poco Series'] },
    ],
    specifications: [
      { label: 'Hardness', value: '9H Diamond-grade surface' },
      { label: 'Package Includes', value: '2x Tempered Glass + 1x Auto Alignment Tray + Wipes' },
      { label: 'Transparency', value: '99.9% High Definition Crystal Optical' },
    ],
  },
];

const wholesaleConfigMap: Record<
  string,
  { wholesale_price: number; set_size: number; wholesale_minimum_sets: number; wholesale_enabled: boolean }
> = {
  'vc-shirt-01': { wholesale_price: 2400, set_size: 12, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'vc-kurti-02': { wholesale_price: 7800, set_size: 10, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'vc-tee-03': { wholesale_price: 2400, set_size: 6, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'vc-cordset-04': { wholesale_price: 5400, set_size: 10, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'vc-jeans-05': { wholesale_price: 4800, set_size: 10, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'vc-lower-06': { wholesale_price: 2400, set_size: 12, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'ksp-holder-01': { wholesale_price: 3000, set_size: 10, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'ksp-foglight-02': { wholesale_price: 4200, set_size: 10, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'ksp-mirrors-03': { wholesale_price: 2400, set_size: 10, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'ksp-seat-04': { wholesale_price: 1800, set_size: 12, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'ksp-horn-05': { wholesale_price: 2100, set_size: 10, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'ksp-indicator-06': { wholesale_price: 1800, set_size: 12, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'kc-charger-01': { wholesale_price: 3000, set_size: 10, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'kc-powerbank-02': { wholesale_price: 6000, set_size: 8, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'kc-earbuds-03': { wholesale_price: 5400, set_size: 10, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'kc-cable-04': { wholesale_price: 1600, set_size: 16, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'kc-cover-05': { wholesale_price: 1800, set_size: 15, wholesale_minimum_sets: 1, wholesale_enabled: true },
  'kc-tempered-06': { wholesale_price: 1250, set_size: 25, wholesale_minimum_sets: 1, wholesale_enabled: true },
};

export const ensureProductWholesaleFields = (p: Product): Product => {
  const custom = wholesaleConfigMap[p.id];
  const setSize = Number(p.set_size || p.setSize || custom?.set_size || 12);
  const wholesaleMinSets = Number(
    p.wholesale_minimum_sets || p.wholesaleMinimumSets || custom?.wholesale_minimum_sets || 1
  );
  const retailPrice = Number(p.retail_price || p.retailPrice || p.salePrice || p.price || 399);

  // Default wholesale price ~60-70% of retail price per piece * set size
  const defaultWholesalePerPiece = Math.round(retailPrice * 0.65);
  const wholesalePrice = Number(
    p.wholesale_price ??
      p.wholesalePrice ??
      custom?.wholesale_price ??
      defaultWholesalePerPiece * setSize
  );
  const wholesaleEnabled = p.wholesale_enabled ?? p.wholesaleEnabled ?? custom?.wholesale_enabled ?? true;

  // Determine clothing status
  const isClothing = p.shopId === 'vinayak-collection';

  let sizeVariants = p.size_variants || p.sizeVariants;
  let sizes = p.sizes || p.clothingDetails?.sizes;

  // Specific initial configuration for demo Oversize T-Shirt
  if (p.id === 'vc-tee-03') {
    sizes = ['M', 'L', 'XL', 'XXL'];
    sizeVariants = [
      { id: 'var-tee-m', productId: p.id, size: 'M', stock_quantity: 15, stock: 15, active: true },
      { id: 'var-tee-l', productId: p.id, size: 'L', stock_quantity: 20, stock: 20, active: true },
      { id: 'var-tee-xl', productId: p.id, size: 'XL', stock_quantity: 15, stock: 15, active: true },
      { id: 'var-tee-xxl', productId: p.id, size: 'XXL', stock_quantity: 12, stock: 12, active: true },
    ];
  } else if (p.id === 'vc-shirt-01' && (!sizeVariants || sizeVariants.length === 0)) {
    sizes = ['S', 'M', 'L', 'XL', 'XXL'];
    sizeVariants = [
      { id: 'var-shirt-s', productId: p.id, size: 'S', stock_quantity: 12, stock: 12, active: true },
      { id: 'var-shirt-m', productId: p.id, size: 'M', stock_quantity: 15, stock: 15, active: true },
      { id: 'var-shirt-l', productId: p.id, size: 'L', stock_quantity: 18, stock: 18, active: true },
      { id: 'var-shirt-xl', productId: p.id, size: 'XL', stock_quantity: 12, stock: 12, active: true },
      { id: 'var-shirt-xxl', productId: p.id, size: 'XXL', stock_quantity: 10, stock: 10, active: true },
    ];
  } else if (isClothing && sizes && sizes.length > 0 && (!sizeVariants || sizeVariants.length === 0)) {
    // Generate initial size variants for other clothing items
    const activeSizesList = sizes;
    const perSize = Math.max(6, Math.floor(p.stock / activeSizesList.length));
    sizeVariants = activeSizesList.map((sz, idx) => ({
      id: `var-${p.id}-${sz.toLowerCase()}`,
      productId: p.id,
      size: sz,
      stock_quantity: idx === 0 ? perSize + (p.stock % activeSizesList.length) : perSize,
      stock: idx === 0 ? perSize + (p.stock % activeSizesList.length) : perSize,
      active: true,
    }));
  }

  // Calculate actual total stock if sizeVariants exist
  let calculatedStock = Number(p.stock ?? 30);
  if (sizeVariants && sizeVariants.length > 0) {
    calculatedStock = sizeVariants.reduce((sum, v) => (v.active !== false ? sum + (v.stock_quantity ?? v.stock ?? 0) : sum), 0);
  }

  const safeImages = Array.isArray(p.images) && p.images.length > 0
    ? p.images
    : [p.image || p.image_url || 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop'];

  const rawMix = p.wholesale_mix_colors || p.wholesaleMixColors || (p.clothingDetails?.colors || ['Black', 'White', 'Blue', 'Red', 'Green', 'Maroon']);
  const normalizedMixColors: string[] = Array.isArray(rawMix)
    ? rawMix.map(String)
    : typeof rawMix === 'string'
    ? (() => {
        try {
          const parsed = JSON.parse(rawMix as string);
          return Array.isArray(parsed) ? parsed.map(String) : [rawMix as string];
        } catch {
          return (rawMix as string).split(',').map((s: string) => s.trim()).filter(Boolean);
        }
      })()
    : ['Black', 'White', 'Blue', 'Red', 'Green', 'Maroon'];

  const catHierarchy = inferCategoryHierarchy(p.categoryName || (p.shopId === 'vinayak-collection' ? 'Shirts' : 'General'), p.shopId);
  const categoryId = p.categoryId || catHierarchy.categoryId;
  const categoryName = p.categoryName || catHierarchy.categoryName;
  const subcategoryId = p.subcategoryId || catHierarchy.subcategoryId;
  const subcategoryName = p.subcategoryName || catHierarchy.subcategoryName;

  const sku = p.sku || (p.shopId === 'vinayak-collection' ? `VC-${categoryId.toUpperCase().slice(0, 3)}-${(p.id || '').slice(-4)}` : `SKU-${(p.id || '').slice(-6)}`);
  const brand = p.brand || (p.shopId === 'vinayak-collection' ? 'Vinayak Originals' : p.shopId === 'kinshuk-spare-parts' ? 'Kinshuk Genuine Spares' : 'Khushi Certified Gadgets');
  const description = p.description || `Premium ${categoryName} guaranteed for quality, authentic design, and verified performance.`;
  const status = (p.status || 'active').toLowerCase() === 'inactive' ? 'inactive' : 'active';

  return {
    ...p,
    sku,
    brand,
    description,
    shortDescription: p.shortDescription || description.slice(0, 80),
    categoryId,
    categoryName,
    subcategoryId,
    subcategoryName,
    status,
    isNew: p.isNew ?? true,
    rating: Number(p.rating || 4.8),
    reviewsCount: Number(p.reviewsCount || 1),
    images: safeImages,
    image: safeImages[0],
    image_url: safeImages[0],
    salePrice: retailPrice,
    retail_price: retailPrice,
    retailPrice: retailPrice,
    wholesale_price: wholesalePrice,
    wholesalePrice: wholesalePrice,
    set_size: setSize,
    setSize: setSize,
    wholesale_minimum_sets: wholesaleMinSets,
    wholesaleMinimumSets: wholesaleMinSets,
    wholesale_enabled: wholesaleEnabled,
    wholesaleEnabled: wholesaleEnabled,
    stock: calculatedStock,
    sizes: sizes || (sizeVariants ? sizeVariants.map((v) => v.size) : undefined),
    size_variants: sizeVariants,
    sizeVariants: sizeVariants,
    has_sizes: Boolean(sizeVariants && sizeVariants.length > 0),
    hasSizes: Boolean(sizeVariants && sizeVariants.length > 0),
    colors: p.colors || p.clothingDetails?.colors,
    color_variants: p.color_variants || p.colorVariants,
    colorVariants: p.color_variants || p.colorVariants,
    wholesale_mix_colors: normalizedMixColors,
    wholesaleMixColors: normalizedMixColors,
    wholesale_set_type: p.wholesale_set_type || 'MIX COLOR SET',
    wholesale_available_sizes: p.wholesale_available_sizes || p.wholesaleAvailableSizes || sizes || (sizeVariants ? sizeVariants.map((v) => v.size) : ['M', 'L', 'XL', 'XXL']),
    wholesaleAvailableSizes: p.wholesale_available_sizes || p.wholesaleAvailableSizes || sizes || (sizeVariants ? sizeVariants.map((v) => v.size) : ['M', 'L', 'XL', 'XXL']),
  };
};

export const initialProducts: Product[] = rawInitialProducts.map(ensureProductWholesaleFields);

export const initialCoupons: Coupon[] = [
  {
    id: 'c-welcome10',
    code: 'WELCOME10',
    description: 'Flat 10% OFF on your first purchase across all three shops.',
    type: 'percentage',
    value: 10,
    minOrder: 499,
    maxDiscount: 200,
    expiryDate: '2026-12-31',
    shopId: 'all',
    usageLimit: 1000,
    usedCount: 142,
    active: true,
  },
  {
    id: 'c-flat100',
    code: 'FLAT100',
    description: 'Instant ₹100 Flat Discount on orders above ₹999.',
    type: 'flat',
    value: 100,
    minOrder: 999,
    expiryDate: '2026-12-31',
    shopId: 'all',
    usageLimit: 500,
    usedCount: 89,
    active: true,
  },
  {
    id: 'c-fashion20',
    code: 'FASHION20',
    description: '20% OFF exclusively on Vinayak Collection Fashion wear.',
    type: 'percentage',
    value: 20,
    minOrder: 799,
    maxDiscount: 350,
    expiryDate: '2026-12-31',
    shopId: 'vinayak-collection',
    usageLimit: 300,
    usedCount: 45,
    active: true,
  },
  {
    id: 'c-insta100',
    code: 'INSTA100',
    description: 'Special ₹100 OFF on orders above ₹999.',
    type: 'flat',
    discount_type: 'flat',
    value: 100,
    discount_value: 100,
    minOrder: 999,
    minimum_order_value: 999,
    maxDiscount: 100,
    maximum_discount: 100,
    startDate: '2026-01-01',
    start_at: '2026-01-01T00:00:00Z',
    expiryDate: '2027-12-31',
    expires_at: '2027-12-31T23:59:59Z',
    usageLimit: 500,
    usage_limit: 500,
    usedCount: 0,
    usage_count: 0,
    perCustomerLimit: 1,
    per_customer_limit: 1,
    applicableShoppingType: 'retail',
    applicable_shopping_type: 'retail',
    shopId: 'all',
    applicable_shop: 'all',
    applicableProducts: 'all',
    applicable_products: 'all',
    active: true,
  },
];

export const initialReviews: CustomerReview[] = [
  {
    id: 'rev-01',
    productId: 'vc-shirt-01',
    author: 'Rajesh Sharma',
    rating: 5,
    date: '12 March 2026',
    title: 'Superb fabric and stitching!',
    comment: 'The linen cotton feels so soft and premium. Fits true to size and looks very elegant for summer parties. Received in 3 days in Delhi NCR.',
    verifiedPurchase: true,
    userCity: 'New Delhi',
  },
  {
    id: 'rev-02',
    productId: 'ksp-holder-01',
    author: 'Vikram Choudhary',
    rating: 5,
    date: '14 March 2026',
    title: 'Unshakeable grip on highway at 100 kmph',
    comment: 'Installed on my Royal Enfield Classic 350. The USB charging works flawlessly with Google Maps open throughout. Genuine all-metal body.',
    verifiedPurchase: true,
    userCity: 'Gurugram',
  },
  {
    id: 'rev-03',
    productId: 'kc-charger-01',
    author: 'Pooja Verma',
    rating: 5,
    date: '10 March 2026',
    title: 'Charges my phone and iPad in minutes',
    comment: 'Very compact GaN adapter. Does not heat up at all like cheap local chargers. Excellent customer service by Khushi Communication.',
    verifiedPurchase: true,
    userCity: 'Jaipur',
  },
];
